# config/config.yaml
default:
  app_name: weather_etl
  environment: dev
  log_level: INFO
  timezone: UTC

paths:
  root: /Users/deepakkumar/Desktop/weather_analyzer
  input:
    dir: data/input
    weather_file: ETL_developer_Case.json
  output:
    dir: data/output
  logs:
    dir: data/logs
  checkpoint:
    dir: data/checkpoints
  state:
    dir: data/state
  metrics:
    dir: data/metrics

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - [%(levelname)s]  - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    detailed:
      format: "%(asctime)s  - %(name)s - [%(levelname)s] - %(module)s.%(funcName)s: - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: detailed
      stream: ext://sys.stdout
    weather_etl_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: weather_etl.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
    extract_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: extract.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
    transform_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: transform.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
    dq_checks_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: dq_checks.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
    analyze_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: analyze.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
    load_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: load.log
      when: midnight
      interval: 1
      backupCount: 30
      encoding: utf8
  loggers:
    weather_etl:
      level: DEBUG
      handlers: [console, weather_etl_handler]
      propagate: false
    weather_etl.extract:
      level: DEBUG
      handlers: [console, extract_handler]
      propagate: false
    weather_etl.transform:
      level: DEBUG
      handlers: [console, transform_handler]
      propagate: false
    weather_etl.dq_checks:
      level: DEBUG
      handlers: [console, dq_checks_handler]
      propagate: false
    weather_etl.analyze:
      level: DEBUG
      handlers: [console, analyze_handler]
      propagate: false
    weather_etl.load:
      level: DEBUG
      handlers: [console, load_handler]
      propagate: false

steps:
  execution_order:
    - extract
    - transform
    - dq_checks
    - analyze
    - load
  
  dependencies:
    transform: 
      - extract
    dq_checks:
      - transform
    analyze:
      - dq_checks
    load:
      - analyze
  save_metadata: true
